version: '3'

services:
  myDB:
    image: postgres:15.3
    container_name: hotel_database_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hotel_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
