CREATE TYPE "board_type" AS ENUM (
  'room_only',
  'bed_and_breakfast',
  'half_board',
  'full_board',
  'all_included'
);

CREATE TABLE "hotel" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "address" varchar(255) NOT NULL,
  "phone" varchar(15) NOT NULL,
  "email" varchar(255) NOT NULL,
  "stars" int
);

CREATE TABLE "hotel_media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(255),
  "hotel_id" int
);

CREATE TABLE "hotel_feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "hotel_feature_mapping" (
  "hotel_id" int,
  "feature_id" int
);

CREATE TABLE "room" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" int,
  "hotel_id" int,
  "room_type_id" int
);

CREATE TABLE "room_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "capacity" int NOT NULL,
  "base_price" decimal(5,2) NOT NULL,
  "hotel_id" int
);

CREATE TABLE "room_feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "room_feature_mapping" (
  "room_type_id" int,
  "room_feature_id" int
);

CREATE TABLE "room_media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(255) UNIQUE NOT NULL,
  "room_type_id" int
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "check_in_date" date NOT NULL,
  "check_out_date" date NOT NULL,
  "customer_id" int,
  "board_plan_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "booking_room_mapping" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "room_id" int
);

CREATE TABLE "board_plan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "price" decimal(5,2),
  "type" board_type,
  "hotel_id" int
);

CREATE TABLE "customer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "first_surname" varchar(255),
  "second_surname" varchar(255),
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "date_of_birth" date NOT NULL,
  "phone" varchar(15) NOT NULL,
  "address" varchar(255),
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "payment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal(10,2),
  "payment_date" date,
  "payment_method" varchar(255),
  "booking_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE INDEX ON "hotel" ("name");

CREATE INDEX ON "hotel" ("address");

CREATE INDEX ON "hotel" ("stars");

CREATE INDEX ON "booking" ("customer_id");

CREATE INDEX ON "booking" ("check_in_date");

CREATE INDEX ON "booking" ("check_out_date");

CREATE INDEX ON "booking_room_mapping" ("booking_id");

CREATE INDEX ON "booking_room_mapping" ("room_id");

ALTER TABLE "booking" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");

ALTER TABLE "room_media" ADD FOREIGN KEY ("room_type_id") REFERENCES "room_type" ("id");

ALTER TABLE "hotel_feature_mapping" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "room_feature_mapping" ADD FOREIGN KEY ("room_type_id") REFERENCES "room_type" ("id");

ALTER TABLE "room_feature_mapping" ADD FOREIGN KEY ("room_feature_id") REFERENCES "room_feature" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("board_plan_id") REFERENCES "board_plan" ("id");

ALTER TABLE "board_plan" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "room" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "room" ADD FOREIGN KEY ("room_type_id") REFERENCES "room_type" ("id");

ALTER TABLE "hotel_feature_mapping" ADD FOREIGN KEY ("feature_id") REFERENCES "hotel_feature" ("id");

ALTER TABLE "hotel_media" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "booking_room_mapping" ADD FOREIGN KEY ("room_id") REFERENCES "room" ("id");

ALTER TABLE "booking_room_mapping" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");
