CREATE TYPE "board_type" AS ENUM (
  'room_only',
  'bed_and_breakfast',
  'half_board',
  'full_board',
  'all_included'
);

CREATE TABLE "hotel" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "address" varchar(255) NOT NULL,
  "phone" varchar(15) NOT NULL,
  "email" varchar(255) NOT NULL,
  "stars" int
);

CREATE TABLE "hotel_media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(255),
  "hotel_id" int
);

CREATE TABLE "hotel_feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "hotel_feature_mapping" (
  "hotel_id" int,
  "feature_id" int
);

CREATE TABLE "room" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" int,
  "hotel_id" int,
  "room_type_id" int
);

CREATE TABLE "room_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "capacity" int NOT NULL,
  "base_price" decimal(5,2) NOT NULL,
  "hotel_id" int
);

CREATE TABLE "room_feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "room_feature_mapping" (
  "room_type_id" int,
  "room_feature_id" int
);

CREATE TABLE "room_media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(255) UNIQUE NOT NULL,
  "room_type_id" int
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "check_in_date" date NOT NULL,
  "check_out_date" date NOT NULL,
  "customer_id" int,
  "board_plan_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "booking_room_mapping" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "room_id" int
);

CREATE TABLE "board_plan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "price" decimal(5,2),
  "type" board_type,
  "hotel_id" int
);

CREATE TABLE "customer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "first_surname" varchar(255),
  "second_surname" varchar(255),
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "date_of_birth" date NOT NULL,
  "phone" varchar(15) NOT NULL,
  "address" varchar(255),
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "payment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal(10,2),
  "payment_date" date,
  "payment_method" varchar(255),
  "booking_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE INDEX ON "hotel" ("name");

CREATE INDEX ON "hotel" ("address");

CREATE INDEX ON "hotel" ("stars");

CREATE INDEX ON "booking" ("customer_id");

CREATE INDEX ON "booking" ("check_in_date");

CREATE INDEX ON "booking" ("check_out_date");

CREATE INDEX ON "booking_room_mapping" ("booking_id");

CREATE INDEX ON "booking_room_mapping" ("room_id");

ALTER TABLE "booking" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");

ALTER TABLE "room_media" ADD FOREIGN KEY ("room_type_id") REFERENCES "room_type" ("id");

ALTER TABLE "hotel_feature_mapping" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "room_feature_mapping" ADD FOREIGN KEY ("room_type_id") REFERENCES "room_type" ("id");

ALTER TABLE "room_feature_mapping" ADD FOREIGN KEY ("room_feature_id") REFERENCES "room_feature" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("board_plan_id") REFERENCES "board_plan" ("id");

ALTER TABLE "board_plan" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "room" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "room" ADD FOREIGN KEY ("room_type_id") REFERENCES "room_type" ("id");

ALTER TABLE "hotel_feature_mapping" ADD FOREIGN KEY ("feature_id") REFERENCES "hotel_feature" ("id");

ALTER TABLE "hotel_media" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "booking_room_mapping" ADD FOREIGN KEY ("room_id") REFERENCES "room" ("id");

ALTER TABLE "booking_room_mapping" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");

-- Insert mock data for db

INSERT INTO hotel (name, address, phone, email, stars)
VALUES
    ('Hotel A', '123 Main St, City A', '123-456-7890', 'hotelA@example.com', 4),
    ('Hotel B', '456 Elm St, City B', '987-654-3210', 'hotelB@example.com', 5);

-- Insert mock data for hotel_media
INSERT INTO hotel_media (url, hotel_id)
VALUES
    ('http://example.com/image1.jpg', 1),
    ('http://example.com/image2.jpg', 2);

-- Insert mock data for hotel_feature
INSERT INTO hotel_feature (name, description)
VALUES
    ('Pool', 'Outdoor swimming pool'),
    ('Gym', 'Fully equipped gym');

-- Insert mock data for hotel_feature_mapping
INSERT INTO hotel_feature_mapping (hotel_id, feature_id)
VALUES
    (1, 1), -- Hotel A has Pool
    (2, 2); -- Hotel B has Gym

-- Insert mock data for room_type
INSERT INTO room_type (name, description, capacity, base_price, hotel_id)
VALUES
    ('Standard', 'Standard room description', 2, 100.00, 1),
    ('Suite', 'Luxurious suite description', 4, 250.00, 1),
    ('Executive', 'Executive room description', 3, 180.00, 2);

-- Insert mock data for room
INSERT INTO room (number, hotel_id, room_type_id)
VALUES
    (101, 1, 1),
    (102, 1, 2),
    (201, 2, 1);

-- Insert mock data for room_feature
INSERT INTO room_feature (name, description)
VALUES
    ('WiFi', 'High-speed internet access'),
    ('Minibar', 'Stocked minibar with refreshments');

-- Insert mock data for room_feature_mapping
INSERT INTO room_feature_mapping (room_type_id, room_feature_id)
VALUES
    (1, 1), -- Standard room has WiFi
    (1, 2), -- Standard room has Minibar
    (2, 1); -- Suite has WiFi

-- Insert mock data for room_media
INSERT INTO room_media (url, room_type_id)
VALUES
    ('http://example.com/room1.jpg', 1),
    ('http://example.com/room2.jpg', 2),
    ('http://example.com/room3.jpg', 3);

-- Insert mock data for board_plan
INSERT INTO board_plan (name, description, price, type, hotel_id)
VALUES
    ('Bed and Breakfast', 'Includes breakfast', 50.00, 'bed_and_breakfast', 1),
    ('Full Board', 'Includes all meals', 100.00, 'full_board', 1);

-- Insert mock data for customer
INSERT INTO customer (name, first_surname, second_surname, email, password, date_of_birth, phone, address)
VALUES
    ('John', 'Doe', NULL, 'johndoe@example.com', 'password123', '1990-05-15', '555-123-4567', '789 Oak St, Town C');

-- Insert mock data for booking
INSERT INTO booking (check_in_date, check_out_date, customer_id, board_plan_id, created_at)
VALUES
    ('2024-08-01', '2024-08-05', 1, 1, NOW()),
    ('2024-09-10', '2024-09-15', 1, 2, NOW());

-- Insert mock data for booking_room_mapping
INSERT INTO booking_room_mapping (booking_id, room_id)
VALUES
    (1, 1), -- Booking 1 has room 101
    (1, 2), -- Booking 1 has room 102
    (2, 3); -- Booking 2 has room 201

-- Insert mock data for payment
INSERT INTO payment (amount, payment_date, payment_method, booking_id, created_at)
VALUES
    (500.00, '2024-07-20', 'Credit Card', 1, NOW()),
    (1000.00, '2024-08-15', 'PayPal', 2, NOW());
